
auth = true # set to true to enable authentication
user = "admin"
pass = "secretpass"

port = 8082
host = "127.0.0.1" # set to false to listen on all interfaces - Set to 0.0.0.0 to allow access from external IPs.
proxy = 1 # trust proxy headers

httplog = "dev"

secret = "a cat" # cookie secret
maxPostSize = "5MB"
apiServer = "http://localhost:12080" # ZoneMTA API location
counterPrefix = "zmta"

# mongodb database name
logsdb = "logs"

retention = 2592000000 # 30 days

mongo = "mongodb://127.0.0.1:27017/logs"

[log]
level = "info"

[logserver]
# set up a log collecting server to catch message updates from zone-mta
enabled = true
protocol = "udp4"
host = false # allow from all
port = 31239

[redis]
# redis is needed to fetch delivery counters
# make sure this configuration matches
host = "localhost"
port = 6379
db = 2
